title: diedromeliga | FrontEndDesign
email: diedromeliga@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Designer, Idealizador e entusiasta do http://buscamoveis.com -
  plataforma que reúne as melhores e mais criativas lojas de móveis e artigos de decoração.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://diedromeliga.com.br # the base hostname & protocol for your site, e.g. http://example.com
default_username: diedromeliga
github_username:  meliga
linkedin_username:  meliga
medium_username: @diedromeliga

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
